12-23 21:12:01 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: テーブル "PLAY_EVOLUTIONS" が見つかりません
Table "PLAY_EVOLUTIONS" not found; SQL statement:
select id, hash, apply_script, revert_script, state, last_problem from play_evolutions where state like 'applying_%' [42102-175]
12-25 11:31:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: シーケンス "USER_ID_SEQ" が見つかりません
Sequence "USER_ID_SEQ" not found; SQL statement:
insert into user (             email, name, password           )           values (             ?, ?, ?           ) [90036-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.schema.Schema.getSequence(Schema.java:501)
	at org.h2.expression.Function.getSequence(Function.java:1455)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1297)
	at org.h2.expression.Function.getValue(Function.java:476)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:266)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:713)
	at org.h2.command.dml.Insert.insertRows(Insert.java:152)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:154)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:140)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
	at anorm.Sql$class.executeUpdate(Anorm.scala:330)
	at anorm.SimpleSql.executeUpdate(Anorm.scala:190)
	at models.User$$anonfun$create$1.apply(User.scala:71)
	at models.User$$anonfun$create$1.apply(User.scala:57)
	at play.api.db.DBApi$class.withConnection(DB.scala:81)
	at play.api.db.BoneCPApi.withConnection(DB.scala:267)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
	at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:162)
	at scala.Option.map(Option.scala:145)
	at play.api.db.DB$.withConnection(DB.scala:162)
	at models.User$.create(User.scala:57)
	at controllers.Application$$anonfun$register$1$$anonfun$apply$8.apply(Application.scala:203)
	at controllers.Application$$anonfun$register$1$$anonfun$apply$8.apply(Application.scala:201)
	at play.api.data.Form.fold(Form.scala:139)
	at controllers.Application$$anonfun$register$1.apply(Application.scala:199)
	at controllers.Application$$anonfun$register$1.apply(Application.scala:198)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432)
	at play.api.mvc.Action$.invokeBlock(Action.scala:556)
	at play.api.mvc.Action$.invokeBlock(Action.scala:555)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12-26 13:39:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER" が見つかりません
Table "USER" not found; SQL statement:
CREATE TABLE task (
id integer NOT NULL DEFAULT nextval('task_id_seq'),
label varchar(255),
progress integer DEFAULT 0,
target datetime DEFAULT null,
seq integer,
create datetime DEFAULT null,
modified datetime DEFAULT null,
user_id integer NOT NULL,
FOREIGN KEY(user_id) REFERENCES user(user_id)
) [42102-175]
12-26 13:39:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:48:50 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:51:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:51:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:52:29 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:53:44 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:53:45 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:53:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:53:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:57:56 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:25 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:31 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:34 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:35 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:37 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 17:59:37 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select * from task [42102-175]
01-05 18:01:45 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:03:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:03:24 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:03:24 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:03:28 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:04:08 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:06:09 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:08:33 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:10:02 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:10:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:10:04 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
select id,label,progress,target from task [42102-175]
01-05 18:41:31 database: close
org.h2.message.DbException: 入出力例外: "java.io.EOFException"; "/home/takedahajime/workspace/todo_Angular_folder/todolist_Angular2/play.h2.db"
IO Exception: "java.io.EOFException"; "/home/takedahajime/workspace/todo_Angular_folder/todolist_Angular2/play.h2.db" [90031-175]
	at org.h2.message.DbException.get(DbException.java:161)
	at org.h2.message.DbException.convertIOException(DbException.java:318)
	at org.h2.store.FileStore.readFully(FileStore.java:268)
	at org.h2.store.PageStore.readPage(PageStore.java:1291)
	at org.h2.store.PageStore.getPage(PageStore.java:738)
	at org.h2.store.PageStreamTrunk$Iterator.next(PageStreamTrunk.java:250)
	at org.h2.store.PageLog.free(PageLog.java:209)
	at org.h2.store.PageStore.compact(PageStore.java:491)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1257)
	at org.h2.engine.Database.close(Database.java:1207)
	at org.h2.engine.DatabaseCloser.run(DatabaseCloser.java:64)
Caused by: org.h2.jdbc.JdbcSQLException: 入出力例外: "java.io.EOFException"; "/home/takedahajime/workspace/todo_Angular_folder/todolist_Angular2/play.h2.db"
IO Exception: "java.io.EOFException"; "/home/takedahajime/workspace/todo_Angular_folder/todolist_Angular2/play.h2.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	... 11 more
Caused by: java.io.EOFException
	at org.h2.store.fs.FileUtils.readFully(FileUtils.java:343)
	at org.h2.store.FileStore.readFully(FileStore.java:266)
	... 8 more
01-08 18:08:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: テーブル "TASK" が見つかりません
Table "TASK" not found; SQL statement:
DROP TABLE task [42102-175]
01-08 18:08:02 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: シーケンス "TASK_ID_SEQ" はすでに存在します
Sequence "TASK_ID_SEQ" already exists; SQL statement:
CREATE SEQUENCE task_id_seq [90035-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:58)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at com.jolbox.bonecp.StatementHandle.execute(StatementHandle.java:254)
	at play.api.db.evolutions.Evolutions$.play$api$db$evolutions$Evolutions$$execute(Evolutions.scala:124)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:266)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1$$anonfun$apply$2.apply(Evolutions.scala:266)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:266)
	at play.api.db.evolutions.Evolutions$$anonfun$applyScript$1.apply(Evolutions.scala:261)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:261)
	at play.api.db.evolutions.EvolutionsPlugin.handleWebCommand(Evolutions.scala:584)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:193)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5$$anonfun$apply$6.apply(ApplicationProvider.scala:192)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
	at scala.collection.immutable.List.foldLeft(List.scala:83)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:192)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1$$anonfun$apply$5.apply(ApplicationProvider.scala:191)
	at scala.Option.flatMap(Option.scala:170)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:191)
	at play.core.ReloadableApplication$$anonfun$handleWebCommand$1.apply(ApplicationProvider.scala:191)
	at scala.Option.orElse(Option.scala:266)
	at play.core.ReloadableApplication.handleWebCommand(ApplicationProvider.scala:189)
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:69)
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:69)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at play.core.server.Server$class.getHandlerFor(Server.scala:69)
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:37)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157)
	at scala.util.Either.fold(Either.scala:99)
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:142)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
01-08 18:08:20 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER" が見つかりません
Table "USER" not found; SQL statement:
select * from user where email = ? [42102-175]
